language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
after_success:
- bash ./deploy.sh
env:
  global:
  - GITHUB_REPO: EnjambreBit/website
  - secure: 1PmAuKdppJXQeD/2aTWhSaRiAl4cw4AMTJkyRSOyH5KDTnTfnhaQmXGoQWnMAKGUzDqIkxNltmZ9hqL4xL3+5wr4nWMHzoPDgo8pjU7Q/lQs0R6SOCnMU5+5ZKMj2e3VblPCYgP+gS6gRYRRkF++4gYZuNO/PMN0hyBOsrhrfi2nMITbedfuEjOab0FetPcK9Z/pnQcpBYi4Gj+Na9Md54t19+G3ToZ+IDOepeKCghHU2tMi8QUUyLZePD6Ms01K3F8mGLtqq8eNtEwRIZkHzq0yrlICoryfRovzWWjrkdh9plsVR+XBGkM01QKn3fhUPuic+fHyTDK0eacinO1p2z4yuVkyALczr/4tiAV4Q1XsMOlzfoEVm1S3+gdNVrmwpdcl4X+Xnlb9ITt+LBnSVlrWN4R1h8p7QP+xO2yat0svPPq/iXIcDCGgc4QburUxnU9vm6gIWTG80Pd9rgDa+IJ6KY6Ch5MwZ3ySTeoAueA+T8ycJbDpDftBAgZuCaM3r3Vu179re0H4oGU2bI/r0Kg7CqemmkurbA4nc6vkNhFR+86U2fHwmZJbBdAEUBdbRIvgSddvZobmJKuCFbz7VR81b9O5VtYp18wc8K5neP7PCuRe602nX6yb68Nus5+hwHqloemHANlRpp9YsvFAZvXAWWFJsq/2b40LtmqQOp4=
  - secure: FaI91bCX1lOTlVgJ3MHEozlGhTYkuDAgteHjREaByJ5TP3oeXqj7H2CTuD5iqUZMuJRq4xiNFie6wvHf6iNYff6Q2RkOa9/h6LWuu3evIOOcwGdajzHt46RAiwhpBSjyT9+wv9fI6KybOwY76W7kU3bbmdA+7j/3VfC/GPYQdom/UH8no5IAXr86gtuEu2Rksa5Pu2A06WVH8+DP6RWlrTc1sYyu92sD6oMy9EPbGxn8shpf3VbwJmIZDSWhm0VibyxSNVPZP8UfZmvgUAVTtacWBjmA1V0ElCvOEeLOf7hOFEzpukdxBJu3alFHoKrGOADkuQeqYCDAOCacWMtvJjC9eie9dsodunWlBZPgT+sCdpKHS7DgetOUXlqUMh2vGVZUWVpShfPPB94gKM7PZONSm/nq7HUBuZ3l8FopovPpeGarreCs4gChm8scaJN9kI5OGAs/vg2y9uD94z4pGJEe0zZvLvvnDDBrbdt7EHCaxx7YmcT+epgFUOB8EltpeX+taBXWG5YySoxWA96Rnf/ZS3MWSBA+YWBdFhULJaoqsr9l+1+hdxAcbmTAv4KgLCECEwBb1y393zcS54GUS8MwsY6Zd58q8ZSZMy3ODO/MNq5BExOwu48YCEaeFo4wsMj4sxjSsyEot0/OIAe8o/I9+Ng5+HVtS/aQXXoIwKs=
